### ISSUE TITLE
Visual Studio Update 3 issues?

### ISSUE THREAD

**Issue by dietrich** [bbqduc/FuzzyOpen#1]
Visual Studio Update 3 may have breaking changes.  Dialog box opens but files are not found when typing in input box.

**Comment by bbqduc** [comment]
Hmm, I can't seem to reproduce it. Does it happen with all solutions for you, or just some specific one?
One way this could happen is if VS has not finished opening projects when the dialog is opened (on startup for example). But that was the same with Update 2 as well so I'm guessing that's not what's happening here.

**Comment by bbqduc** [comment]
I think this might have been fixed in one of the Update 3 hotfixes, so I'm closing it for now. If it is still reproducing for you please reopen!
