### ISSUE TITLE
Please stop being so awesome because it is making my head hurt.   :-)

### ISSUE THREAD

**Issue by mkamoski1** [bbqduc/FuzzyOpen#2]
...

Dear FuzzyOpen Developer,

Please stop being so awesome because it is making my head hurt.   :-)

Seriously.

FuzzyOpen is an absolutively awesome VS 2015 Extension.

I could not find a way to contact you-- your Git profile does not seem to accept comments or questions and etc.

Had to say it, you save my life. I mean, seriously, no joke, I was literally surrounded by about a thousand blood thristy zombie-vampire hybrids, who were intent on ending my poor live and having me for a breakfast snack. The behemoth that is VS 2015, which is at times both awesome and at times a total PITA that make my eyeballs explode, stopped working and started breaking. The VS stupid (cause it is broken) built-in search from Solution Explorer crashes VS with NotResponding every time I try to use it, a known bug (Google that)  and is claimed as fixed in Update 2, but sadly and more is the pity it is not actually fixed as of Update 3. So, I could not search for files in VS, which is a crazy thing to need to do (I get it) but I was stuck until the shining light and beauty of FuzzyOpen.

Seriously, man (woman? whatever you are), thank you SO much.

I will, no joke, be sending you at least 1 Million Dollars USD in pure silver bars. So, on the lookout for that, as it will hopefully make your day. I will be delivering that by helicopter to you within 5 minutes of when I click Submit on this "issue" and so I hope that helps.

Peace out.

(Note, yes, I know, this is a shameless, but Fair Use, Leafy Parody, and if you get that reference then GREAT but if not then that's OK too. You are, nonetheless, on my List Of Awesome People for life, for sure.)

-- Mark Kamoski

...

**Comment by bbqduc** [comment]
Thanks for the kind words! Good to hear that the extension has been of use to you. I'm closing this issue, but if you have anything you would like to be improved about the tool let me know!
